Move From AnyKernel2 To LazyFlasher

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,224 +1,108 @@
 #!/sbin/sh
-# AnyKernel2 Backend (DO NOT CHANGE)
-# osm0sis @ xda-developers
+# Kernel Flasher installer backend
 
-OUTFD=/proc/self/fd/$2;
-ZIPFILE="$3";
-DIR=`dirname "$ZIPFILE"`;
+tmp=/tmp/kernel-flasher
 
-ui_print() {
-  until [ ! "$1" ]; do
-    echo -e "ui_print $1\nui_print" > $OUTFD;
-    shift;
-  done;
+if [ "$3" ]; then
+	zip=$3
+	console=/proc/$$/fd/$2
+	# write the location of the console buffer to /tmp/console for other scripts to use
+	echo "$console" > /tmp/console
+else
+	console=$(cat /tmp/console)
+	[ "$console" ] || console=/proc/$$/fd/1
+fi
+
+print() {
+	if [ "$1" ]; then
+		echo "ui_print $1" > "$console"
+	else
+		echo "ui_print  " > "$console"
+	fi
+	echo
 }
-show_progress() { echo "progress $1 $2" > $OUTFD; }
-file_getprop() { $bb grep "^$2=" "$1" | $bb cut -d= -f2-; }
-int2ver() {
-  if [ "$1" -eq "$1" ] 2>/dev/null; then 
-    echo "$1.0.0";
-  elif [ ! "$(echo "$1" | $bb cut -d. -f3)" ]; then
-    echo "$1.0";
-  else
-    echo "$1";
-  fi;
-}
-cleanup() {
-  cd /tmp;
-  rm -rf /tmp/anykernel;
-}
-debugging() {
-  case $(basename "$ZIPFILE" .zip) in
-    *-debugging)
-      ui_print " ";
-      ui_print "Creating debugging archive in zip directory...";
-      $bb tar -czvf "$DIR/anykernel2-$(date +%Y-%m-%d_%H%M%S)-debug.tgz" /tmp/*;
-    ;;
-  esac;
-}
-is_mounted() { $bb mount | $bb grep " $1 "; }
-unmount_all() {
-  (umount /system;
-  if [ -d /system_root -a ! -f /system/build.prop ]; then
-    umount /system_root;
-  fi;
-  umount /system;
-  umount /vendor;
-  umount /data) 2>/dev/null;
-}
+
 abort() {
-  ui_print "$*";
-  debugging;
-  if [ ! -f anykernel.sh -o "$(file_getprop anykernel.sh do.cleanuponabort 2>/dev/null)" == 1 ]; then
-    cleanup;
-  fi;
-  unmount_all;
-  exit 1;
+	[ "$1" ] && {
+		print "Error: $1"
+		print "Aborting..."
+	}
+	cleanup
+	print "Failed to patch boot image!"
+	exit 1
 }
 
-show_progress 1.34 4;
-ui_print " ";
-cleanup;
-mkdir -p /tmp/anykernel/bin;
-cd /tmp/anykernel;
-unzip -o "$ZIPFILE";
-if [ $? != 0 -o -z "$(ls tools)" ]; then
-  abort "Unzip failed. Aborting...";
-fi;
-bb=/tmp/anykernel/tools/busybox;
-chmod 755 $bb;
-$bb chmod -R 755 tools bin;
+cleanup() {
+	[ "$zip" ] && rm /tmp/console
+	umount /system
+}
 
-if [ -f banner ]; then
-  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
-    ui_print "$line";
-  done < banner;
-  ui_print " ";
-  ui_print " ";
-fi;
+extract() {
+	rm -rf "$2"
+	mkdir -p "$2"
+	unzip -o "$1" -d "$2" || abort "Failed to extract zip to $2!"
+}
 
-ui_print "$(file_getprop anykernel.sh kernel.string)";
-if [ -f version ]; then
-  ui_print " ";
-  while IFS='' read -r line || $bb [[ -n "$line" ]]; do
-    ui_print "$line";
-  done < version;
-  ui_print " ";
-fi;
-ui_print " ";
-ui_print " ";
-ui_print " ";
+setperm() {
+	find "$3" -type d -exec chmod "$1" {} \;
+	find "$3" -type f -exec chmod "$2" {} \;
+}
 
-unmount_all;
-if [ ! "$(is_mounted /system)" ]; then
-  $bb mount -o ro -t auto /system;
-fi;
-($bb mount -o ro -t auto /vendor;
-$bb mount /data) 2>/dev/null;
-if [ -f /system/system/build.prop ]; then
-  umount /system;
-  (umount /system;
-  mkdir /system_root) 2>/dev/null;
-  $bb mount -o ro -t auto /dev/block/bootdevice/by-name/system /system_root;
-  $bb mount -o bind /system_root/system /system;
-fi;
-savedpath="$LD_LIBRARY_PATH";
-savedpre="$LD_PRELOAD";
-unset LD_LIBRARY_PATH;
-unset LD_PRELOAD;
+mount() {
+	mountpoint -q "$1" || /sbin/busybox mount -o rw "$1" || abort "Unable to mount $1 as rw!"
+	>> "$1/.rw" && return || /sbin/busybox mount -o remount,rw "$1"
+	>> "$1/.rw" && return || abort "Unable to write to $1!"
+}
 
-if [ ! "$(getprop 2>/dev/null)" ]; then
-  getprop() {
-    local propval="$(file_getprop /default.prop $1 2>/dev/null)";
-    test "$propval" || local propval="$(file_getprop /system/build.prop $1 2>/dev/null)";
-    test "$propval" && echo "$propval" || echo "";
-  }
-elif [ ! "$(getprop ro.product.device 2>/dev/null)" -a ! "$(getprop ro.build.product 2>/dev/null)" ]; then
-  getprop() {
-    ($(which getprop) | $bb grep "$1" | $bb cut -d[ -f3 | $bb cut -d] -f1) 2>/dev/null;
-  }
-fi;
+umount() {
+	mountpoint -q "$1" || return 0
+	rm -f "$1/.rw"
+	/sbin/busybox umount "$1"
+}
 
-if [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ]; then
-  ui_print "Checking device...";
-  device="$(getprop ro.product.device)";
-  product="$(getprop ro.build.product)";
-  for testname in $(file_getprop anykernel.sh 'device.name.*'); do
-    if [ "$device" == "$testname" -o "$product" == "$testname" ]; then
-      ui_print $testname;
-      match=1;
-      break;
-    fi;
-  done;
-  ui_print " ";
-  if [ ! "$match" ]; then
-    abort "Unsupported device. Aborting...";
-  fi;
-fi;
+print "#######################################"
+print "#             N00b Kernel             #"
+print "#      by chankruze | version 1.0     #"
+print "#     Prepare To Inject N00bKernel    #"
+print "#######################################"
 
-supported_ver="$(file_getprop anykernel.sh supported.versions | $bb tr -d '[:space:]')";
-if [ "$supported_ver" ]; then
-  ui_print "Checking Android version...";
-  android_ver="$(file_getprop /system/build.prop ro.build.version.release)";
-  if [ "$(echo $supported_ver | $bb grep -)" ]; then
-    lo_ver=$(echo $supported_ver | $bb cut -d- -f1);
-    hi_ver=$(echo $supported_ver | $bb cut -d- -f2);
-    if [ "$(echo -e "$(int2ver $hi_ver)\n$(int2ver $lo_ver)\n$(int2ver $android_ver)" | $bb sort -g | $bb grep -n "$(int2ver $android_ver)" | $bb grep '^2:')" ]; then
-      supported=1;
-    fi;
-  else
-    for ver in $(echo $supported_ver | $bb sed 's;,; ;g'); do
-      if [ "$(int2ver $ver)" == "$(int2ver $android_ver)" ]; then
-        supported=1;
-        break;
-      fi;
-    done;
-  fi;
-  if [ "$supported" ]; then
-    ui_print "$android_ver";
-    ui_print " ";
-  else
-    ui_print " ";
-    abort "Unsupported Android version. Aborting...";
-  fi;
-fi;
+# Unpack the installer
+[ "$zip" ] && {
+	print "Unpacking the installer..."
+	extract "$zip" "$tmp"
+}
+cd "$tmp"
 
-ui_print "Installing...";
-for i in $($bb --list); do
-  $bb ln -s $bb bin/$i;
-done;
-if [ $? != 0 -o -z "$(ls bin)" ]; then
-  abort "Recovery busybox setup failed. Aborting...";
-fi;
-PATH="/tmp/anykernel/bin:$PATH" $bb ash anykernel.sh $2;
-if [ $? != 0 ]; then
-  abort;
-fi;
+. config.sh
 
-if [ "$(file_getprop anykernel.sh do.modules)" == 1 ]; then
-  ui_print " ";
-  ui_print "Pushing modules...";
-  $bb mount -o rw,remount -t auto /system;
-  $bb mount -o rw,remount -t auto /vendor 2>/dev/null;
-  cd /tmp/anykernel/modules;
-  for module in $(find . -name '*.ko'); do
-    modtarget=$(echo $module | $bb cut -c2-);
-    if [ ! -e $modtarget ]; then
-      case $module in
-        */vendor/*) modcon=vendor;;
-        *) modcon=system;;
-      esac;
-    fi;
-    if [ "$(is_mounted $modtarget)" ]; then
-      $bb mount -o rw,remount -t auto $modtarget;
-    fi;
-    mkdir -p $(dirname $modtarget);
-    $bb cp -rLf $module $modtarget;
-    $bb chown 0:0 $modtarget;
-    $bb chmod 644 $modtarget;
-    if [ "$modcon" ]; then
-      chcon "u:object_r:${modcon}_file:s0" $modtarget;
-    fi;
-    if [ "$(is_mounted $modtarget)" ]; then
-      $bb mount -o ro,remount -t auto $modtarget;
-    fi;
-  done;
-  cd /tmp/anykernel;
-  $bb mount -o ro,remount -t auto /system;
-  $bb mount -o ro,remount -t auto /vendor 2>/dev/null;
-fi;
+[ "$device_names" ] && {
+	if ! command -v getprop; then
+		print "Warning: getprop not found! Skipping device check!"
+		return
+	fi
+	print "Checking device compatibility..."
+	match=0
+	ro_product_device=$(getprop ro.product.device)
+	ro_product_model=$(getprop ro.product.model)
+	ro_build_product=$(getprop ro.build.product)
+	for i in $device_names; do
+		[ "$ro_product_device" = "$i" ] ||
+		[ "$ro_product_model" = "$i" ] ||
+		[ "$ro_build_product" = "$i" ] &&
+			match=1
+	done
+	[ $match != 1 ] && abort "Unsupported device"
+}
 
-debugging;
+mount /system
+# mount /data
 
-if [ "$(file_getprop anykernel.sh do.cleanup)" == 1 ]; then
-  cleanup;
-fi;
+setperm 0755 0755 "$bin"
 
-test "$savedpath" && export LD_LIBRARY_PATH="$savedpath";
-test "$savedpre" && export LD_PRELOAD="$savedpre";
+print "Running boot image patcher..."
+sh boot-patcher.sh || abort
 
-unmount_all;
+print "Boot image patching complete"
 
-ui_print "N00bKernel Ejected !";
-ui_print " ";
-ui_print "Now Die!";
+cleanup
+print "Done installing!"
